# 以Scikit-learn SVM進行鳶尾花(Iris)品種的辨識

## 載入相關套件

In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

## 載入資料集

In [2]:
X, y = datasets.load_iris(return_X_y=True)

## 資料分割

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

## 特徵縮放

In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

## 模型訓練

In [10]:
from sklearn.svm import SVC

clf = SVC(probability=True)
clf.fit(X_train_std, y_train)

SVC(probability=True)

## 模型評分

In [11]:
# 計算準確率
y_pred = clf.predict(X_test_std)
print(f'{accuracy_score(y_test, y_pred)*100:.2f}%') 

100.00%


In [12]:
clf.support_vectors_

array([[-1.67184579, -1.6957369 , -1.41981813, -1.2136154 ],
       [-0.60722701,  0.71111547, -1.30787452, -1.08335256],
       [-1.08039091, -0.16410357, -1.25190271, -1.34387823],
       [-1.79013676, -0.38290833, -1.36384632, -1.34387823],
       [-1.55355481,  1.148725  , -1.58773354, -1.34387823],
       [-0.25235408,  2.89916309, -1.30787452, -1.08335256],
       [-0.96209993,  0.49231071, -1.19593091, -0.95308973],
       [-1.90842774, -0.16410357, -1.53176174, -1.47414106],
       [ 0.45739177, -1.6957369 ,  0.31530784,  0.08901294],
       [ 0.93055567,  0.05470119,  0.48322325,  0.3495386 ],
       [ 1.04884665, -0.60171309,  0.53919506,  0.21927577],
       [ 0.10251885, -0.38290833,  0.37127964,  0.3495386 ],
       [-0.37064506, -0.16410357,  0.37127964,  0.3495386 ],
       [-0.84380896, -0.82051786,  0.03544881,  0.21927577],
       [ 0.93055567, -0.16410357,  0.65113867,  0.61006427],
       [ 0.69397372, -0.60171309,  0.42725145,  0.3495386 ],
       [-1.08039091, -2.

In [13]:
clf.support_

array([ 34,  68,  71,  91,  94,  99, 100, 119,   8,   9,  23,  31,  33,
        45,  48,  49,  52,  62,  65,  70,  79,  80,  82,  85,  93,  97,
        98, 102,  10,  11,  16,  17,  19,  21,  24,  27,  44,  47,  64,
        67,  72,  77,  88,  89, 112, 117])

In [14]:
clf.predict_proba(X_test)

array([[0.31200265, 0.30892925, 0.3790681 ],
       [0.27924154, 0.28418253, 0.43657593],
       [0.31426633, 0.31036102, 0.37537266],
       [0.27858745, 0.28396668, 0.43744587],
       [0.30900388, 0.30700212, 0.38399401],
       [0.31217161, 0.30903499, 0.37879339],
       [0.3120006 , 0.30892431, 0.37907508],
       [0.31442297, 0.3104593 , 0.37511774],
       [0.25522482, 0.26662586, 0.47814933],
       [0.31443167, 0.31046369, 0.37510465],
       [0.28408765, 0.28767204, 0.42824031],
       [0.27853438, 0.28395018, 0.43751544],
       [0.29195562, 0.29623574, 0.41180863],
       [0.31460321, 0.31057027, 0.37482652],
       [0.28600633, 0.29252745, 0.42146622],
       [0.31419664, 0.31031701, 0.37548634],
       [0.31437885, 0.31043112, 0.37519003],
       [0.3146347 , 0.31058943, 0.37477587],
       [0.31243689, 0.3092018 , 0.37836131],
       [0.31223646, 0.30907699, 0.37868655],
       [0.3123927 , 0.30918301, 0.37842429],
       [0.27381341, 0.28030622, 0.44588038],
       [0.

In [15]:
clf.predict_log_proba(X_test)

array([[-1.16474358, -1.17464299, -0.97003942],
       [-1.27567812, -1.25813855, -0.82879297],
       [-1.15751448, -1.17001908, -0.979836  ],
       [-1.27802327, -1.25889836, -0.82680231],
       [-1.17440145, -1.18090064, -0.95712834],
       [-1.1642022 , -1.17430077, -0.97076436],
       [-1.16475016, -1.17465897, -0.97002098],
       [-1.15701616, -1.16970248, -0.98051534],
       [-1.36561048, -1.32190889, -0.7378322 ],
       [-1.1569885 , -1.16968833, -0.98055024],
       [-1.25847246, -1.2459342 , -0.84807076],
       [-1.27821377, -1.25895648, -0.82664329],
       [-1.23115346, -1.21659971, -0.88719652],
       [-1.15644309, -1.1693451 , -0.98129196],
       [-1.25174135, -1.22919677, -0.86401564],
       [-1.15773623, -1.17016088, -0.97953318],
       [-1.15715651, -1.16979323, -0.98032263],
       [-1.15634299, -1.16928341, -0.98142711],
       [-1.16335279, -1.17376114, -0.97190568],
       [-1.16399451, -1.17416487, -0.97104645],
       [-1.16349423, -1.1738219 , -0.971